# Generated by Django 4.0.6 on 2023-02-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='edicao',
            name='data_postagem',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Data da Postagem'),
        ),
    ]
