# Generated by Django 4.0.6 on 2023-02-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornal', '0003_comentario_data_postagem_noticia_data_postagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Cadastro'),
        ),
    ]
